from fastapi import APIRouter, Depends, Query
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session
from typing import Optional
from datetime import date, datetime, timezone, timedelta
import pandas as pd
from io import BytesIO
from enum import Enum
from openpyxl import Workbook
from openpyxl.utils.dataframe import dataframe_to_rows

from app.db.deps import get_db
from app.auth.dependencies import get_current_user

from app.models import issue_receipt as issue_receipt_model
from app.models.new_tyre_grn import Tyre


class ActionTypeFilter(str, Enum):
    ALL = "All"
    ISSUE = "Issue"
    RECEIPT = "Receipt"


# IST Timezone
IST = timezone(timedelta(hours=5, minutes=30))


def _make_ist(dt):
    """Convert UTC datetime to IST and make it timezone-naive for Excel"""
    if dt is None:
        return None
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    ist_dt = dt.astimezone(IST)
    return ist_dt.replace(tzinfo=None)


router = APIRouter()

@router.get("/issue-receipt-report", summary="Download Issue & Receipt Excel Report")
def get_issue_receipt_report(
    date_from: Optional[date] = Query(None, description="Start Date (YYYY-MM-DD)"),
    date_to: Optional[date] = Query(None, description="End Date (YYYY-MM-DD)"),
    vehicle_no: Optional[str] = Query(None, description="Vehicle Number"),
    tyre_no: Optional[str] = Query(None, description="Tyre Number"),
    action_type: ActionTypeFilter = Query(ActionTypeFilter.ALL, description="Select Report Type"),
    db: Session = Depends(get_db),
    current_user=Depends(get_current_user)
):
    query = db.query(issue_receipt_model.IssueReceipt)

    # Filter by Action Type
    if action_type != ActionTypeFilter.ALL:
        query = query.filter(
            issue_receipt_model.IssueReceipt.action_type == action_type.value)
    if date_from:
        query = query.filter(issue_receipt_model.IssueReceipt.ir_date >= date_from)
    if date_to:
        query = query.filter(issue_receipt_model.IssueReceipt.ir_date <= date_to)
    if vehicle_no:
        query = query.filter(
            issue_receipt_model.IssueReceipt.vehicle_no.ilike(f"%{vehicle_no}%"))
    if tyre_no:
        query = query.filter(
            issue_receipt_model.IssueReceipt.tyre_no.ilike(f"%{tyre_no}%"))

    results = query.order_by(
        issue_receipt_model.IssueReceipt.ir_date.desc()
    ).all()

    report_data = []

    for ir in results:
        tyre = (
            db.query(Tyre)
            .filter(Tyre.tyre_no == ir.tyre_no)
            .first()
            if ir.tyre_no
            else None
        )

        report_data.append({
            "IR No": ir.ir_no,
            "Action Type": ir.action_type,
            "IR Date": ir.ir_date,
            "Office ID": ir.office_id,
            "Vehicle No": ir.vehicle_no,
            "Vehicle KM": ir.vehicle_km,
            "Tyre No": ir.tyre_no,

            # Receipt Fields
            "Convert to Stepney": ir.convert_to_stepney,
            "Outer NSD": ir.outer_nsd,
            "Center NSD": ir.center_nsd,
            "Center2 NSD": ir.center2_nsd,
            "Inner NSD": ir.inner_nsd,
            "Average NSD": ir.average_nsd,

            # Issue Fields
            "Issue to Stepney": ir.issue_to_stepney,
            "Wheel Position": ir.wheel_position,
            "Remarks": ir.remarks,
            "Removal Reason": ir.removal_reason,

            "Status": ir.status,
            "Created By": ir.created_by,
            "Created At": _make_ist(ir.created_at),

            # Tyre Information
            "Tyre Brand": tyre.brand if tyre else None,
            "Tyre Size": tyre.size if tyre else None,
            "Production Month": tyre.production_month if tyre else None,
            "Tyre GRN No": tyre.grn_no if tyre else None,
            "Tyre Current Status": tyre.current_status if tyre else None,
        })

    # Create dataframe
    df = pd.DataFrame(report_data)
    output = BytesIO()

    # Dynamic Sheet Name
    if action_type == ActionTypeFilter.ISSUE:
        base_name = "Issue_Report"

    elif action_type == ActionTypeFilter.RECEIPT:
        base_name = "Receipt_Report"

    else:
        base_name = "Issue_Receipt_Report"

    # Create Workbook
    wb = Workbook()

    # SUMMARY SHEET
    summary_ws = wb.active
    summary_ws.title = "Summary"

    generated_at = datetime.now(IST).replace(tzinfo=None)

    summary_data = [
        ["Report Name", base_name],
        ["Generated At", generated_at],
        ["Generated By", ""],
        ["From Date", date_from if date_from else ""],
        ["To Date", date_to if date_to else ""],
    ]

    for row in summary_data:
        summary_ws.append(row)

    # Adjust summary sheet widths
    for column in summary_ws.columns:
        max_length = 0
        column_letter = column[0].column_letter

        for cell in column:
            try:
                if cell.value:
                    max_length = max(max_length, len(str(cell.value)))
            except:
                pass

        summary_ws.column_dimensions[column_letter].width = min(max_length + 5, 50)

    # CREATE SEPARATE SHEET FOR EACH TYRE
    if not df.empty:

        # Group dataframe by tyre number
        grouped = df.groupby("Tyre No")
        for tyre_number, tyre_df in grouped:
            # Excel sheet name max length = 31
            sheet_title = str(tyre_number)[:31] if tyre_number else "Unknown_Tyre"

            ws = wb.create_sheet(title=sheet_title)

            # Write dataframe rows
            for r in dataframe_to_rows(tyre_df, index=False, header=True):
                ws.append(r)

            # Auto adjust widths
            for column in ws.columns:
                max_length = 0
                column_letter = column[0].column_letter

                for cell in column:
                    try:
                        if cell.value:
                            max_length = max(max_length, len(str(cell.value)))
                    except:
                        pass

                adjusted_width = min(max_length + 2, 50)
                ws.column_dimensions[column_letter].width = adjusted_width

    else:
        # Empty sheet fallback
        empty_sheet_name = (
        str(tyre_no)[:31]
        if tyre_no
        else "No_Data"
    )
    ws = wb.create_sheet(title=empty_sheet_name)
    ws.append(["No records found"])

    # Save workbook
    wb.save(output)
    output.seek(0)

    # FILE NAME
    now_ist = datetime.now(IST).replace(tzinfo=None)
    filename = f"{base_name}_{now_ist.strftime('%Y%m%d_%H%M%S')}.xlsx"

    return StreamingResponse(
        output,
        media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        headers={
            "Content-Disposition": f"attachment; filename={filename}"
        }
    )