from fastapi import APIRouter, Depends, Query
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session
from typing import Optional
from datetime import date, datetime, timedelta, timezone
import pandas as pd
from io import BytesIO
from enum import Enum
from openpyxl import Workbook
from openpyxl.utils.dataframe import dataframe_to_rows

from app.db.deps import get_db
from app.auth.dependencies import get_current_user

from app.models.new_tyre_grn import NewGRN, Tyre
from app.models.fleet_vendor import FleetVendor
from app.models.office import Office   


class GRNTypeFilter(str, Enum):
    ALL = "All"
    NEW = "New"
    NEW_REMOULD = "New-Remould"
    CHASSIS = "Chassis"


# IST Conversion
IST = timezone(timedelta(hours=5, minutes=30))

def _make_ist(dt):
    if dt is None:
        return None
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    ist_dt = dt.astimezone(IST)
    return ist_dt.replace(tzinfo=None)


router = APIRouter()

@router.get("/new-grn-report", summary="Download New GRN / Tyre Purchase Report")
def get_new_grn_report(
    date_from: Optional[date] = Query(None, description="Start Date (YYYY-MM-DD)"),
    date_to: Optional[date] = Query(None, description="End Date (YYYY-MM-DD)"),
    grn_type: GRNTypeFilter = Query(GRNTypeFilter.ALL, description="GRN Type"),
    tyre_no: Optional[str] = Query(None, description="Tyre Number"),
    db: Session = Depends(get_db),
    current_user=Depends(get_current_user)
):
    query = db.query(NewGRN)

    if grn_type != GRNTypeFilter.ALL:
        query = query.filter(NewGRN.type == grn_type.value)
    if date_from:
        query = query.filter(NewGRN.grn_date >= date_from)
    if date_to:
        query = query.filter(NewGRN.grn_date <= date_to)
    if tyre_no:
        query = query.join(NewGRN.tyres).filter(Tyre.tyre_no.ilike(f"%{tyre_no}%"))

    grns = query.order_by(NewGRN.grn_date.desc()).all()

    report_data = []
    for grn in grns:
        office = db.query(Office).filter(Office.id == grn.office_id).first()
        office_name = office.name if office else grn.office_id

        vendor = db.query(FleetVendor).filter(FleetVendor.id == grn.vendor_id).first()
        vendor_name = vendor.name if vendor else (grn.vendor_id or "N/A")

        for tyre in grn.tyres:
            if tyre_no and tyre_no.lower() not in tyre.tyre_no.lower():
                continue

            grn_type_display = grn.type
            if isinstance(grn_type_display, Enum):
                grn_type_display = grn_type_display.value

            report_data.append({
                "GRN No": grn.grn_no,
                "GRN Date": grn.grn_date,
                "GRN Type": grn_type_display,
                "Office Name": office_name,
                "Vendor Name": vendor_name,
                "Vendor Office": grn.vendor_office,
                "Challan No": grn.challan_no,
                "Challan Date": grn.challan_date,
                "Total Tyres": grn.total_tyre_count,
                "Total Amount": grn.total_amount,
                "Total GST": grn.total_gst,
                "Total Discount": grn.total_discount,
                "Remark": grn.remark,
                "Created By": grn.created_by,
                "Created At": _make_ist(grn.created_at),
                "Tyre No": tyre.tyre_no,
                "Brand": tyre.brand,
                "Size": tyre.size,
                "Production Month": tyre.production_month,
                "Rubber Brand": tyre.rubber_brand,
                "Rubber Type": tyre.rubber_type,
                "Amount": tyre.amount,
                "Discount": tyre.discount,
                "CGST": tyre.cgst,
                "SGST": tyre.sgst,
                "IGST": tyre.igst,
                "Total GST (Tyre)": tyre.total_gst,
                "Total Amount (Tyre)": tyre.total_amt,
                "Current Status": tyre.current_status,
            })

    df = pd.DataFrame(report_data)
    output = BytesIO()

    if grn_type == GRNTypeFilter.ALL:
        report_name = "New GRN Report"
        base_name = "New_GRN_Report"
    else:
        report_name = f"{grn_type.value} GRN Report"
        base_name = f"{grn_type.value}_GRN_Report"

    generated_at = datetime.now(IST).replace(tzinfo=None)
    generated_by = getattr(current_user, 'full_name', None) or getattr(current_user, 'username', '')

    wb = Workbook()

    # ── SUMMARY SHEET ──────────────────────────────────────────────
    summary_ws = wb.active
    summary_ws.title = "Summary"

    summary_data = [
        ["Report Name",  report_name],
        ["Generated At", generated_at],
        ["Generated By", generated_by],
        ["From Date",    date_from if date_from else ""],
        ["To Date",      date_to   if date_to   else ""],
        ["GRN Type",     grn_type.value],
        ["Tyre No",      tyre_no   if tyre_no   else ""],
        ["Total Records", len(report_data)],
    ]

    for row in summary_data:
        summary_ws.append(row)

    for col in summary_ws.columns:
        max_length = 0
        col_letter = col[0].column_letter
        for cell in col:
            try:
                if cell.value:
                    max_length = max(max_length, len(str(cell.value)))
            except:
                pass
        summary_ws.column_dimensions[col_letter].width = min(max_length + 5, 50)

    # ── REPORT SHEET ───────────────────────────────────────────────
    report_ws = wb.create_sheet(title="New_GRN_Report")

    if df.empty:
        report_ws.append(["No records found"])
    else:
        for r in dataframe_to_rows(df, index=False, header=True):
            report_ws.append(r)

    for col in report_ws.columns:
        max_length = 0
        col_letter = col[0].column_letter
        for cell in col:
            try:
                if cell.value:
                    max_length = max(max_length, len(str(cell.value)))
            except:
                pass
        report_ws.column_dimensions[col_letter].width = min(max_length + 2, 50)

    wb.save(output)
    output.seek(0)

    now_ist = datetime.now(IST).replace(tzinfo=None)
    filename = f"{base_name}_{now_ist.strftime('%Y%m%d_%H%M%S')}.xlsx"

    return StreamingResponse(
        output,
        media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        headers={"Content-Disposition": f"attachment; filename={filename}"}
    )