from fastapi import APIRouter, Depends, Query
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session
from typing import Optional
from datetime import date, datetime, timedelta, timezone
import pandas as pd
from io import BytesIO
from enum import Enum
from openpyxl import Workbook
from openpyxl.utils.dataframe import dataframe_to_rows

from app.db.deps import get_db_tyre as get_db
from app.auth.dependencies import get_current_user

from app.models import transaction as transaction_model   
from app.models.new_tyre_grn import Tyre
from app.models.fleet_vendor import FleetVendor
from app.models.office import Office

class GRNTypeFilter(str, Enum):
    ALL = "All"
    SEND_REMOULD = "Send-Remould"
    SEND_CLAIM = "Send-Claim"
    SCRAP = "Scrap"
    RESELL = "Resell"
    THEFT = "Theft"
    RECEIVE_REMOULD = "Receive-Remould"
    RECEIVE_CLAIM = "Receive-Claim"

# IST Timezone
IST = timezone(timedelta(hours=5, minutes=30))

def _make_ist(dt):
    """Convert UTC datetime to IST and make it timezone-naive for Excel"""
    if dt is None:
        return None
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    ist_dt = dt.astimezone(IST)
    return ist_dt.replace(tzinfo=None)

router = APIRouter()

@router.get("/transaction-report", summary="Download Transaction Excel Report")
def get_transaction_report(
    date_from: Optional[date] = Query(None, description="Start Date (YYYY-MM-DD)"),
    date_to: Optional[date] = Query(None, description="End Date (YYYY-MM-DD)"),
    grn_type: GRNTypeFilter = Query(GRNTypeFilter.ALL, description="Select GRN Type"),
    tyre_no: Optional[str] = Query(None, description="Tyre Number"),
    db: Session = Depends(get_db),
    current_user=Depends(get_current_user)
):
    query = db.query(transaction_model.Transaction)

    if grn_type != GRNTypeFilter.ALL:
        query = query.filter(
            transaction_model.Transaction.grn_type == grn_type.value)

    if date_from:
        query = query.filter(transaction_model.Transaction.date >= date_from)
    if date_to:
        query = query.filter(transaction_model.Transaction.date <= date_to)

    if tyre_no:
        query = query.join(transaction_model.TransactionDetail).filter(
            transaction_model.TransactionDetail.tyre_no.ilike(f"%{tyre_no}%")
        )

    transactions = query.order_by(transaction_model.Transaction.date.desc()).all()

    report_data = []
    for trans in transactions:
        office = db.query(Office).filter(Office.id == trans.office_id).first()
        office_name = office.name if office else trans.office_id

        vendor = db.query(FleetVendor).filter(FleetVendor.id == trans.vendor_id).first()
        vendor_name = vendor.name if vendor else (trans.vendor_id or "N/A")

        for detail in trans.details:
            tyre = db.query(Tyre).filter(Tyre.tyre_no == detail.tyre_no).first() if detail.tyre_no else None

            grn_type_display = trans.grn_type
            if isinstance(grn_type_display, Enum):
                grn_type_display = grn_type_display.value

            report_data.append({
                "GRN No": trans.grn_no,
                "GRN Type": grn_type_display,
                "Transaction Date": trans.date,
                "Office Name": office_name,
                "Vendor Name": vendor_name,
                "Total Tyres": trans.total_tyres,
                "Total Amount": trans.total_amount,
                "Remark / Reason": trans.remark_reason,
                "Place": trans.place,
                "Created By": trans.created_by,
                "Created At": _make_ist(trans.created_at),

                "Tyre No": detail.tyre_no,
                "Vehicle No": detail.vehicle_no,
                "Reason": detail.reason,
                "NSD": detail.nsd,
                "KM Run": detail.km_run,
                "Detail Remark": detail.remark,

                "Tyre Brand": tyre.brand if tyre else None,
                "Tyre Size": tyre.size if tyre else None,
                "Production Month": tyre.production_month if tyre else None,
                "Tyre Current Status": tyre.current_status if tyre else None,
            })

    df = pd.DataFrame(report_data)
    output = BytesIO()

    if grn_type == GRNTypeFilter.ALL:
        report_name = "Transaction Report"
        base_name = "Transaction_Report"
    else:
        report_name = f"{grn_type.value} GRN Report"
        base_name = f"{grn_type.value}_GRN_Report"

    wb = Workbook()

    # ── SUMMARY SHEET ──────────────────────────────────────────────
    summary_ws = wb.active
    summary_ws.title = "Summary"

    generated_at = datetime.now(IST).replace(tzinfo=None)
    generated_by = getattr(current_user, 'full_name', None) or getattr(current_user, 'username', '')

    summary_data = [
        ["Report Name",   report_name],
        ["Generated At",  generated_at],
        ["Generated By",  generated_by],
        ["From Date",     date_from if date_from else ""],
        ["To Date",       date_to   if date_to   else ""],
        ["GRN Type",      grn_type.value],
    ]

    for row in summary_data:
        summary_ws.append(row)

    for column in summary_ws.columns:
        max_length = 0
        column_letter = column[0].column_letter
        for cell in column:
            try:
                if cell.value:
                    max_length = max(max_length, len(str(cell.value)))
            except:
                pass
        summary_ws.column_dimensions[column_letter].width = min(max_length + 5, 50)

    # ── ONE SHEET PER TYRE ─────────────────────────────────────────
    if not df.empty:
        grouped = df.groupby("Tyre No")
        for tyre_number, tyre_df in grouped:
            sheet_title = str(tyre_number)[:31] if tyre_number else "Unknown_Tyre"
            ws = wb.create_sheet(title=sheet_title)

            for r in dataframe_to_rows(tyre_df, index=False, header=True):
                ws.append(r)

            for column in ws.columns:
                max_length = 0
                column_letter = column[0].column_letter
                for cell in column:
                    try:
                        if cell.value:
                            max_length = max(max_length, len(str(cell.value)))
                    except:
                        pass
                ws.column_dimensions[column_letter].width = min(max_length + 2, 50)
    else:
        sheet_title = str(tyre_no)[:31] if tyre_no else "No_Data"
        ws = wb.create_sheet(title=sheet_title)
        ws.append(["No records found"])

    wb.save(output)
    output.seek(0)

    now_ist = datetime.now(IST).replace(tzinfo=None)
    filename = f"{base_name}_{now_ist.strftime('%Y%m%d_%H%M%S')}.xlsx"

    return StreamingResponse(
        output,
        media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        headers={"Content-Disposition": f"attachment; filename={filename}"}
    )